### ISSUE TITLE
There's no Redux Code

### ISSUE THREAD

**Issue by Aarbel** [mschwarzmueller/reactjs-redux-basics#2]
Hi Max, thank you for your amazing video, just missing the redux part of the code in these files ;) could be great to follow the videos and directly test code

**Comment by BramEsposito** [comment]
@Aarbel I think you forgot to check out the right branch? 
![screenshot 2017-12-19 11 52 05](https://user-images.githubusercontent.com/168336/34153660-1d0fca00-e4b3-11e7-8f0b-553c79d12adc.png)
